import {PrismaClient,RoleCode,DepartmentCode} from '@prisma/client';import bcrypt from 'bcryptjs';const db=new PrismaClient();
const permissions=['dashboard:view','attendance:self','attendance:all','leave:create','approval:department','approval:all','customer:view','customer:create','customer:manage','order:create','order:self','order:all','order:review_manager','order:review_finance','order:review_admin','order:tech','invoice:manage','payment:manage','performance:self','performance:all','statistics:view','user:manage','settings:manage','logs:view'];
const rolePermissions:Record<RoleCode,string[]>={
  ADMIN:permissions,
  SALES_MANAGER:['dashboard:view','customer:view','customer:create','customer:manage','order:create','order:self','order:review_manager','performance:self','attendance:self','leave:create'],
  SALES_EMPLOYEE:['dashboard:view','customer:view','customer:create','customer:manage','order:create','order:self','performance:self','attendance:self','leave:create'],
  FINANCE_MANAGER:['dashboard:view','customer:view','order:all','order:review_finance','invoice:manage','payment:manage','performance:all','statistics:view','attendance:self','leave:create'],
  FINANCE_EMPLOYEE:['dashboard:view','customer:view','order:all','order:review_finance','invoice:manage','payment:manage','performance:all','statistics:view','attendance:self','leave:create'],
  TECH_MANAGER:['dashboard:view','customer:view','order:tech','attendance:self','leave:create'],
  TECH_EMPLOYEE:['dashboard:view','customer:view','order:tech','attendance:self','leave:create'],
};
async function main(){const password=process.env.SEED_PASSWORD||'ChangeMe123!',passwordHash=await bcrypt.hash(password,12);await db.companySetting.upsert({where:{id:'company'},update:{},create:{id:'company',companyName:'星尧企业'}});for(const [code,name] of Object.entries({FINANCE:'财务部',SALES:'销售部',TECH:'技术部'}))await db.department.upsert({where:{code:code as DepartmentCode},update:{name},create:{code:code as DepartmentCode,name}});const permissionIds:Record<string,string>={};for(const code of permissions){const p=await db.permission.upsert({where:{code},update:{name:code},create:{code,name:code}});permissionIds[code]=p.id}const roleIds={} as Record<RoleCode,string>;for(const roleCode of Object.values(RoleCode)){const role=await db.role.upsert({where:{code:roleCode},update:{name:roleCode},create:{code:roleCode,name:roleCode}});roleIds[roleCode]=role.id;await db.rolePermission.deleteMany({where:{roleId:role.id}});await db.rolePermission.createMany({data:rolePermissions[roleCode].map(code=>({roleId:role.id,permissionId:permissionIds[code]}))})}await db.user.upsert({where:{username:'admin'},update:{roleId:roleIds.ADMIN,status:'ACTIVE'},create:{username:'admin',name:'系统管理员',passwordHash,roleId:roleIds.ADMIN,jobTitle:'系统管理员',employmentStartDate:new Date(),workYears:0,annualLeaveDays:0}});for(const [years,days] of [[0,0],[1,1],[2,2],[3,3],[5,5],[10,10]])await db.annualLeaveRule.upsert({where:{minWorkYears:years},update:{days},create:{minWorkYears:years,days}});console.log(`权限和基础数据已更新，仅确保管理员账号存在。管理员密码：${password}`)}main().finally(()=>db.$disconnect());
