'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';import {useRouter} from 'next/navigation';import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';

export default function ForgotPassword(){
  const router=useRouter(),[email,setEmail]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[sending,setSending]=useState(false),[cooldown,setCooldown]=useState(0);
  useEffect(()=>{if(cooldown<=0)return;const timer=setInterval(()=>setCooldown(v=>Math.max(0,v-1)),1000);return()=>clearInterval(timer)},[cooldown]);
  async function sendCode(){if(!email){setMessage('请先填写邮箱');return}setSending(true);setMessage('');const res=await fetch('/api/auth/email-code',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,purpose:'RESET'})}),body=await res.json();setSending(false);setMessage(res.ok?'验证码已发送，请检查邮箱':body.message);if(res.ok)setCooldown(60)}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage('');const fd=new FormData(e.currentTarget),password=String(fd.get('password')||''),confirm=String(fd.get('confirm')||'');if(password!==confirm){setLoading(false);setMessage('两次输入的新密码不一致');return}const res=await fetch('/api/auth/password-reset',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,code:fd.get('code'),password})}),body=await res.json();setLoading(false);if(!res.ok){setMessage(body.message);return}setMessage('密码已重置，正在返回登录页…');setTimeout(()=>router.push('/login'),900)}
  return <main className="grid min-h-screen place-items-center bg-zinc-950 p-5"><form onSubmit={submit} className="w-full max-w-sm rounded-2xl bg-white p-8 shadow-2xl"><h1 className="text-2xl font-semibold">找回密码</h1><p className="mt-2 text-sm text-zinc-500">通过账户已绑定的邮箱验证身份并设置新密码。</p><label className="mt-7 block text-sm font-medium">邮箱</label><Input name="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" className="mt-2" required/><label className="mt-5 block text-sm font-medium">邮箱验证码</label><div className="mt-2 flex gap-2"><Input name="code" inputMode="numeric" maxLength={6} placeholder="6位验证码" required/><Button type="button" variant="outline" onClick={sendCode} disabled={sending||cooldown>0} className="shrink-0">{cooldown>0?`${cooldown}秒`:sending?'发送中…':'获取验证码'}</Button></div><label className="mt-5 block text-sm font-medium">新密码</label><Input name="password" type="password" minLength={8} autoComplete="new-password" className="mt-2" required/><label className="mt-5 block text-sm font-medium">确认新密码</label><Input name="confirm" type="password" minLength={8} autoComplete="new-password" className="mt-2" required/>{message&&<p className={`mt-4 rounded-lg p-3 text-sm ${message.includes('已发送')||message.includes('已重置')?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{message}</p>}<Button disabled={loading} className="mt-6 w-full">{loading?'正在重置…':'重置密码'}</Button><Link href="/login" className="mt-5 block text-center text-sm text-zinc-500 hover:text-zinc-900">返回登录</Link></form></main>
}
