ALTER TYPE "public"."OrderStatus" ADD VALUE IF NOT EXISTS 'PENDING_FINANCE';
ALTER TYPE "public"."OrderApprovalStatus" ADD VALUE IF NOT EXISTS 'PENDING_FINANCE';
ALTER TYPE "public"."OrderApprovalStatus" ADD VALUE IF NOT EXISTS 'FINANCE_REJECTED';
