ALTER TYPE "public"."OrderStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "public"."OrderStatus" ADD VALUE IF NOT EXISTS 'PENDING_SALES_MANAGER';
ALTER TYPE "public"."OrderStatus" ADD VALUE IF NOT EXISTS 'PENDING_ADMIN';
ALTER TYPE "public"."OrderStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "public"."OrderStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "public"."OrderStatus" ADD VALUE IF NOT EXISTS 'TECH_COMPLETED';
ALTER TYPE "public"."OrderStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "public"."ProcessStatus" ADD VALUE IF NOT EXISTS 'PARTIAL';
